apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-com-ssl
  namespace: istio-system
spec:
  commonName: "*.suriya-demo.com"
  secretName: demo-com-ssl
  issuerRef:
    kind: ClusterIssuer
    name: certificate-cluster-prod
    # name: certificate-cluster-staging
    # group: cert-manager.io
  dnsNames:
  - "*.suriya-demo.com"