# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: suriya-cert
#   namespace: istio-system
# spec:
#   secretName: suriya-cert
#   duration: 2160h # 90d
#   renewBefore: 360h # 15d
#   isCA: false
#   privateKey:
#     algorithm: RSA
#     encoding: PKCS1
#     size: 2048
#   usages:
#     - server auth
#     - client auth
#   dnsNames:
#     - "suriya.com"
#   issuerRef:
#     name: letsencrypt-certificate-cluster
#     kind: ClusterIssuer
#     group: cert-manager.io

# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: suriya-certtificate
#   namespace: istio-system
# spec:
#   secretName: suriya-cert-tls
#   issuerRef:
#     # The issuer created previously
#     name: letsencrypt-certificate-cluster
#     kind: ClusterIssuer
#   dnsNames:
#   - suriya.com

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: suriya-ssl
  namespace: istio-system
spec:
  secretName: suriya-cert-tls
  issuerRef:
    # The issuer created previously
    name: letsencrypt-certificate-cluster
  dnsNames:
  - "suriya.com"