apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-certificate-cluster
  namespace: istio-system
spec:
  acme:
    email: suriya.infortech9@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-tls
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: suriya-demo
          # Secret key reference to the service account created above
          serviceAccountSecretRef:
            name: cert-manager-credentials
            key: suriya-demo-77de251688a0.json
