installCRDs: true

extraArgs:
  - --enable-certificate-owner-ref=true
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
  # - --dns01-recursive-nameservers=kube-dns.kube-system.svc.cluster.local:53

# prometheus:
#   enabled: true
#   servicemonitor:
#     enabled: true