replicas: 1
minimumMasterNodes: 1

ingress:
  enabled: true
  hosts:
    - host: elasticsearch.suriya.com
      paths:
        - path: /
  
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi