# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-production
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: suriya.infortech9@gmail.com
#     privateKeySecretRef:
#       name: letsencrypt-production
#     solvers:
#       - dns01:
#           cloudflare:
#             email: suriya.infortech9@gmail.com
#             apiTokenSecretRef:
#               name: cloudflare-token-secret
#               key: cloudflare-token
#         selector:
#           dnsZones:
#             - "example.com"

# issuer-lets-encrypt-production.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: suriya.infortech9@gmail.com # ❗ Replace this with your email address
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - http01:
        ingress:
          name: web-ingress